// Code generated by MockGen. DO NOT EDIT.
// Source: creation.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	config "github.com/sp0x/torrentd/config"
	indexer "github.com/sp0x/torrentd/indexer"
	categories "github.com/sp0x/torrentd/indexer/categories"
	reflect "reflect"
)

// MockScope is a mock of Scope interface
type MockScope struct {
	ctrl     *gomock.Controller
	recorder *MockScopeMockRecorder
}

// MockScopeMockRecorder is the mock recorder for MockScope
type MockScopeMockRecorder struct {
	mock *MockScope
}

// NewMockScope creates a new mock instance
func NewMockScope(ctrl *gomock.Controller) *MockScope {
	mock := &MockScope{ctrl: ctrl}
	mock.recorder = &MockScopeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockScope) EXPECT() *MockScopeMockRecorder {
	return m.recorder
}

// Lookup mocks base method
func (m *MockScope) Lookup(config config.Config, key string) (indexer.Indexer, error) {

	ret := m.ctrl.Call(m, "Lookup", config, key)
	ret0, _ := ret[0].(indexer.Indexer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup
func (mr *MockScopeMockRecorder) Lookup(config, key interface{}) *gomock.Call {

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockScope)(nil).Lookup), config, key)
}

// CreateAggregateForCategories mocks base method
func (m *MockScope) CreateAggregateForCategories(config config.Config, cats []categories.Category) (indexer.Indexer, error) {

	ret := m.ctrl.Call(m, "CreateAggregateForCategories", config, cats)
	ret0, _ := ret[0].(indexer.Indexer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAggregateForCategories indicates an expected call of CreateAggregateForCategories
func (mr *MockScopeMockRecorder) CreateAggregateForCategories(config, cats interface{}) *gomock.Call {

	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAggregateForCategories", reflect.TypeOf((*MockScope)(nil).CreateAggregateForCategories), config, cats)
}
